server:
  port: 9001
 
logging:
    level: info
    level.org.hibernate.SQL: debug
    pattern:
        console: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: sareh
    password: 1234567
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/banking
 